// <auto-generated/>
#pragma warning disable CS0618
using Cpnucleo.WebApi.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Cpnucleo.WebApi.Client.Api.Impediment
{
    /// <summary>
    /// Builds and executes requests for operations under \api\impediment
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImpedimentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImpedimentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/impediment?id={id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImpedimentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/impediment?id={id}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes the impediments specified by the provided Ids. Validates existence of each, removes them, updates the repository, and commits the transaction.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentRemoveImpedimentResponse"/></returns>
        /// <param name="body">Request model for removing an impediment.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentRemoveImpedimentResponse?> DeleteAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentRemoveImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentRemoveImpedimentResponse> DeleteAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentRemoveImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentRemoveImpedimentResponse>(requestInfo, global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentRemoveImpedimentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetches the impediment matching the provided Id. Returns 404 if not found, otherwise returns the impediment data mapped to a DTO.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentGetImpedimentByIdResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentGetImpedimentByIdResponse?> GetAsync(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder.ImpedimentRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentGetImpedimentByIdResponse> GetAsync(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder.ImpedimentRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentGetImpedimentByIdResponse>(requestInfo, global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentGetImpedimentByIdResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the impediment identified by the provided Id with given data. Validates existence and returns whether the update was successful.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentUpdateImpedimentResponse"/></returns>
        /// <param name="body">Request model for updating an impediment.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentUpdateImpedimentResponse?> PatchAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentUpdateImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentUpdateImpedimentResponse> PatchAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentUpdateImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentUpdateImpedimentResponse>(requestInfo, global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentUpdateImpedimentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new impediment record with the given data and custom Id. Validates uniqueness and returns the created impediment&apos;s data.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentCreateImpedimentResponse"/></returns>
        /// <param name="body">Request model for creating a new impediment.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentCreateImpedimentResponse?> PostAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentCreateImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentCreateImpedimentResponse> PostAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentCreateImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentCreateImpedimentResponse>(requestInfo, global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentCreateImpedimentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes the impediments specified by the provided Ids. Validates existence of each, removes them, updates the repository, and commits the transaction.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request model for removing an impediment.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentRemoveImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentRemoveImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, "{+baseurl}/api/impediment", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Fetches the impediment matching the provided Id. Returns 404 if not found, otherwise returns the impediment data mapped to a DTO.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder.ImpedimentRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder.ImpedimentRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates the impediment identified by the provided Id with given data. Validates existence and returns whether the update was successful.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request model for updating an impediment.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentUpdateImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentUpdateImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, "{+baseurl}/api/impediment", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Creates a new impediment record with the given data and custom Id. Validates uniqueness and returns the created impediment&apos;s data.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request model for creating a new impediment.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentCreateImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentCreateImpedimentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/api/impediment", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ImpedimentRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Fetches the impediment matching the provided Id. Returns 404 if not found, otherwise returns the impediment data mapped to a DTO.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ImpedimentRequestBuilderGetQueryParameters 
        {
            /// <summary>Gets or sets the unique identifier for the impediment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id")]
            public string? Id { get; set; }
#nullable restore
#else
            [QueryParameter("id")]
            public string Id { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ImpedimentRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder.ImpedimentRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ImpedimentRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ImpedimentRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
