// <auto-generated/>
#pragma warning disable CS0618
using Cpnucleo.WebApi.Client.Api.Appointment;
using Cpnucleo.WebApi.Client.Api.Appointments;
using Cpnucleo.WebApi.Client.Api.Assignment;
using Cpnucleo.WebApi.Client.Api.AssignmentImpediment;
using Cpnucleo.WebApi.Client.Api.AssignmentImpediments;
using Cpnucleo.WebApi.Client.Api.AssignmentType;
using Cpnucleo.WebApi.Client.Api.AssignmentTypes;
using Cpnucleo.WebApi.Client.Api.Assignments;
using Cpnucleo.WebApi.Client.Api.Impediment;
using Cpnucleo.WebApi.Client.Api.Impediments;
using Cpnucleo.WebApi.Client.Api.Organization;
using Cpnucleo.WebApi.Client.Api.Organizations;
using Cpnucleo.WebApi.Client.Api.Project;
using Cpnucleo.WebApi.Client.Api.Projects;
using Cpnucleo.WebApi.Client.Api.User;
using Cpnucleo.WebApi.Client.Api.UserAssignment;
using Cpnucleo.WebApi.Client.Api.UserAssignments;
using Cpnucleo.WebApi.Client.Api.UserProject;
using Cpnucleo.WebApi.Client.Api.UserProjects;
using Cpnucleo.WebApi.Client.Api.Users;
using Cpnucleo.WebApi.Client.Api.Workflow;
using Cpnucleo.WebApi.Client.Api.Workflows;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Cpnucleo.WebApi.Client.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The appointment property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Appointment.AppointmentRequestBuilder Appointment
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Appointment.AppointmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The appointments property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Appointments.AppointmentsRequestBuilder Appointments
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Appointments.AppointmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assignment property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Assignment.AssignmentRequestBuilder Assignment
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Assignment.AssignmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assignmentImpediment property</summary>
        public global::Cpnucleo.WebApi.Client.Api.AssignmentImpediment.AssignmentImpedimentRequestBuilder AssignmentImpediment
        {
            get => new global::Cpnucleo.WebApi.Client.Api.AssignmentImpediment.AssignmentImpedimentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assignmentImpediments property</summary>
        public global::Cpnucleo.WebApi.Client.Api.AssignmentImpediments.AssignmentImpedimentsRequestBuilder AssignmentImpediments
        {
            get => new global::Cpnucleo.WebApi.Client.Api.AssignmentImpediments.AssignmentImpedimentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assignments property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Assignments.AssignmentsRequestBuilder Assignments
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Assignments.AssignmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assignmentType property</summary>
        public global::Cpnucleo.WebApi.Client.Api.AssignmentType.AssignmentTypeRequestBuilder AssignmentType
        {
            get => new global::Cpnucleo.WebApi.Client.Api.AssignmentType.AssignmentTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assignmentTypes property</summary>
        public global::Cpnucleo.WebApi.Client.Api.AssignmentTypes.AssignmentTypesRequestBuilder AssignmentTypes
        {
            get => new global::Cpnucleo.WebApi.Client.Api.AssignmentTypes.AssignmentTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The impediment property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder Impediment
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Impediment.ImpedimentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The impediments property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Impediments.ImpedimentsRequestBuilder Impediments
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Impediments.ImpedimentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organization property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder Organization
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizations property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder Organizations
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The project property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Project.ProjectRequestBuilder Project
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Project.ProjectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Cpnucleo.WebApi.Client.Api.User.UserRequestBuilder User
        {
            get => new global::Cpnucleo.WebApi.Client.Api.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userAssignment property</summary>
        public global::Cpnucleo.WebApi.Client.Api.UserAssignment.UserAssignmentRequestBuilder UserAssignment
        {
            get => new global::Cpnucleo.WebApi.Client.Api.UserAssignment.UserAssignmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userAssignments property</summary>
        public global::Cpnucleo.WebApi.Client.Api.UserAssignments.UserAssignmentsRequestBuilder UserAssignments
        {
            get => new global::Cpnucleo.WebApi.Client.Api.UserAssignments.UserAssignmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userProject property</summary>
        public global::Cpnucleo.WebApi.Client.Api.UserProject.UserProjectRequestBuilder UserProject
        {
            get => new global::Cpnucleo.WebApi.Client.Api.UserProject.UserProjectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userProjects property</summary>
        public global::Cpnucleo.WebApi.Client.Api.UserProjects.UserProjectsRequestBuilder UserProjects
        {
            get => new global::Cpnucleo.WebApi.Client.Api.UserProjects.UserProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Users.UsersRequestBuilder Users
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflow property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Workflow.WorkflowRequestBuilder Workflow
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Workflow.WorkflowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflows property</summary>
        public global::Cpnucleo.WebApi.Client.Api.Workflows.WorkflowsRequestBuilder Workflows
        {
            get => new global::Cpnucleo.WebApi.Client.Api.Workflows.WorkflowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
