name: "cpnucleo-dev"

# Extension defining common API configuration for development builds.
x-common-api-dev: &common-api-dev
  env_file:
    - .env    
  environment:
    ASPNETCORE_ENVIRONMENT: Development
    Otlp__Endpoint: http://otel-lgtm:4317
    OTEL_METRIC_EXPORT_INTERVAL: 5000

services:
  webapi1-cpnucleo: &webapi1
    <<: *common-api-dev
    build:
      context: ./src/
      dockerfile: ./WebApi/Dockerfile
      args:
        CACHE: "true"      
        AOT: false
        TRIM: false
        EXTRA_OPTIMIZE: false
        BUILD_CONFIGURATION: Debug
    ports:
      # Development mapping similar to default: host port 5100 => container port (as defined in Dockerfile)
      - "5100:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  webapi2-cpnucleo:
    <<: [*webapi1, *common-api-dev]
    ports:
      # Development mapping: host port 5111 => container port 8080
      - "5111:8080"

  identityapi-cpnucleo:
    <<: *common-api-dev
    build:
      context: ./src/
      dockerfile: ./IdentityApi/Dockerfile
      args:
        CACHE: "true"
        AOT: false
        TRIM: false
        EXTRA_OPTIMIZE: false
        BUILD_CONFIGURATION: Debug
    ports:
      # Development mapping: host port 5200 => container port 5050
      - "5200:5050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  otel-lgtm:
    image: grafana/otel-lgtm
    volumes:
      - otel_lgtm_data:/data
    ports:
      # Exposing ports for OpenTelemetry collector in development
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

volumes:
  otel_lgtm_data:
    driver: local
    labels:
      - "com.example.service=otel-lgtm"

networks:
  default:
    name: cpnucleo_network
    driver: bridge
    driver_opts:
      com.example.description: "Default network for cpnucleo services"