name: "cpnucleo-default"

# Extension defining common configuration for API services in the default configuration.
x-common-api: &common-api
  depends_on:
    db:
      condition: service_healthy
  env_file:
    - .env      
  environment:
    ConnectionStrings__DefaultConnection: ${API_CONNECTION_STRING}

services:
  webapi1-cpnucleo:
    <<: *common-api
    image: jonathanperis/cpnucleo-web-api:latest
    container_name: webapi1-cpnucleo
    ports:
      - "5100:8080"
      
  webapi2-cpnucleo:
    <<: *common-api
    image: jonathanperis/cpnucleo-web-api:latest
    container_name: webapi2-cpnucleo
    ports:
      - "5111:8080"

  identityapi-cpnucleo:
    <<: *common-api
    image: jonathanperis/cpnucleo-identity-api:latest
    container_name: identityapi-cpnucleo
    ports:
      - "5200:5050"

  db:
    image: postgres:16.7
    container_name: db-cpnucleo
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5      
    ports:
      - "5432:5432"      
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0

  nginx:
    image: nginx
    container_name: nginx-cpnucleo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - webapi1-cpnucleo
      - webapi2-cpnucleo
      - identityapi-cpnucleo
    ports:
      - "9999:9999"

volumes:
  db-data:
    driver: local