name: "cpnucleo-dev"

# Extension defining common API configuration for development builds.
x-common-api-dev: &common-api-dev
  build:
    context: ./src/
  env_file:
    - .env    
  environment:
    ASPNETCORE_ENVIRONMENT: Development
    Otlp__Endpoint: http://otel-lgtm:4317
    OTEL_METRIC_EXPORT_INTERVAL: 5000

services:
  webapi1-cpnucleo:
    <<: *common-api-dev
    build:
      dockerfile: ./WebApi/Dockerfile
      args:
        AOT: false
        TRIM: false
        EXTRA_OPTIMIZE: false
        BUILD_CONFIGURATION: Debug
    networks:
      - cpnucleo_network

  webapi2-cpnucleo:
    <<: *common-api-dev
    image: jonathanperis/cpnucleo-web-api:latest
    networks:
      - cpnucleo_network

  identityapi-cpnucleo:
    <<: *common-api-dev
    build:
      dockerfile: ./IdentityApi/Dockerfile
      args:
        AOT: false
        TRIM: false
        EXTRA_OPTIMIZE: false
        BUILD_CONFIGURATION: Debug
    networks:
      - cpnucleo_network

  otel-lgtm:
    image: grafana/otel-lgtm
    volumes:
      - otel-lgtm-data:/data
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    networks:
      - cpnucleo_network

volumes:
  otel-lgtm-data:
    driver: local

networks:
  cpnucleo_network:
    driver: bridge    