name: "cpnucleo"

services:
  webapi1-cpnucleo: &webapi1
    build:
      context: ./src/
      dockerfile: ./WebApi/Dockerfile
      args:
        AOT: false
        TRIM: true
        EXTRA_OPTIMIZE: false
        BUILD_CONFIGURATION: Release
    container_name: webapi1-cpnucleo
    depends_on:
      - db
    restart: always
    ports:
      - "5100:8080"    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Username=postgres;Password=postgres;Database=cpnucleo;Minimum Pool Size=10;Maximum Pool Size=10;Multiplexing=true;

  webapi2-cpnucleo:
    <<: *webapi1
    container_name: webapi2-cpnucleo
    ports:
      - "5111:8080"  

  identityapi-cpnucleo:
    build:
      context: ./src/
      dockerfile: ./IdentityApi/Dockerfile
      args:
        AOT: false
        TRIM: true
        EXTRA_OPTIMIZE: false
        BUILD_CONFIGURATION: Release
    container_name: identityapi-cpnucleo
    depends_on:
      - db
    restart: always      
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Username=postgres;Password=postgres;Database=cpnucleo;Minimum Pool Size=10;Maximum Pool Size=10;Multiplexing=true;
    ports:
      - "5200:5050"

  db:
    image: postgres:16.7
    container_name: db-cpnucleo
    restart: always
    depends_on:
      - postgres-exporter      
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cpnucleo
    ports:
      - "5432:5432"
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0

  nginx:
    image: nginx
    container_name: nginx-cpnucleo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - webapi1-cpnucleo
      - webapi2-cpnucleo
      - identityapi-cpnucleo
    ports:
      - "9999:9999"
      
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter-service
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/cpnucleo?sslmode=disable"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-service
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
      image: grafana/grafana-oss
      container_name: grafana-service        
      ports:
        - "3000:3000"
      volumes:
        - "./grafana/config/:/etc/grafana/"
        - "./grafana/dashboards/:/var/lib/grafana/dashboards/"
      depends_on:
        - prometheus

volumes:
  db-data:
    driver: local
  prometheus-data:
    driver: local