global using Domain.Models;
global using FastEndpoints;
global using FastEndpoints.Testing;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using Shouldly;
global using System.Net;
global using Xunit;
global using WebApi.Integration.Tests.Hosts;
