using System.Text.Json;
using System.Text.RegularExpressions;

namespace Architecture.Tests;

/// <summary>
/// Owner requirement: every page of the WebClient and of the documentation site is an Astro page,
/// no client UI framework is installed, and no hand-written HTML page is served outside Astro.
/// The same rule is enforced by src/WebClient/src/guarantees/astro-pages.test.ts (including the
/// built dist/ output) and scripts/check-docs-drift.py (including the built docs/out output).
/// </summary>
public class AstroPagesTests
{
    private static readonly string[] ForbiddenFrameworkPackages =
    [
        "react", "react-dom", "preact", "vue", "svelte", "solid-js", "lit", "alpinejs",
        "@builder.io/qwik", "@builder.io/qwik-city", "@qwik.dev/core", "@qwik.dev/router",
        "@astrojs/react", "@astrojs/vue", "@astrojs/svelte", "@astrojs/solid-js",
        "@astrojs/preact", "@astrojs/lit", "@astrojs/alpinejs",
    ];

    private static readonly string[] DependencySections =
        ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies", "overrides"];

    public static TheoryData<string> AstroSites => new() { "src/WebClient", "docs" };

    [Theory]
    [MemberData(nameof(AstroSites))]
    public void EveryPage_ShouldBeAnAstroFile(string site)
    {
        var pagesDirectory = GetRepositoryPath(Path.Combine(site, "src", "pages"));
        Directory.Exists(pagesDirectory).Should().BeTrue($"{site} must keep its Astro pages directory");

        var pages = Directory.EnumerateFiles(pagesDirectory, "*", SearchOption.AllDirectories).ToList();

        pages.Should().NotBeEmpty($"{site} must have at least one page; a missing directory must not silently pass");
        pages.Where(path => !path.EndsWith(".astro", StringComparison.Ordinal))
            .Select(path => Path.GetRelativePath(GetRepositoryPath(site), path))
            .Should().BeEmpty($"every {site} page must be an .astro file (dynamic routes such as [resource].astro are fine)");
    }

    [Theory]
    [MemberData(nameof(AstroSites))]
    public void PublicAssets_ShouldNotContainHandWrittenHtmlPages(string site)
    {
        var publicDirectory = GetRepositoryPath(Path.Combine(site, "public"));
        var htmlPages = Directory.Exists(publicDirectory)
            ? Directory.EnumerateFiles(publicDirectory, "*", SearchOption.AllDirectories)
                .Where(path => path.EndsWith(".html", StringComparison.OrdinalIgnoreCase) || path.EndsWith(".htm", StringComparison.OrdinalIgnoreCase))
                .Select(path => Path.GetRelativePath(GetRepositoryPath(site), path))
            : [];

        htmlPages.Should().BeEmpty($"{site} must serve pages generated by Astro, not standalone HTML from public/");
    }

    [Theory]
    [MemberData(nameof(AstroSites))]
    public void Packages_ShouldNotDependOnClientUiFrameworks(string site)
    {
        using var manifest = JsonDocument.Parse(File.ReadAllText(GetRepositoryPath(Path.Combine(site, "package.json"))));
        var packageNames = DependencySections
            .Where(section => manifest.RootElement.TryGetProperty(section, out _))
            .SelectMany(section => manifest.RootElement.GetProperty(section).EnumerateObject().Select(property => property.Name))
            .ToHashSet(StringComparer.Ordinal);

        packageNames.Should().Contain("astro", $"{site} is an Astro site");
        packageNames.Intersect(ForbiddenFrameworkPackages).Should().BeEmpty($"{site} must not add a client rendering framework");

        var astroConfig = File.ReadAllText(GetRepositoryPath(Path.Combine(site, "astro.config.mjs")));
        ForbiddenFrameworkPackages
            .Where(name => astroConfig.Contains($"'{name}'", StringComparison.Ordinal) || astroConfig.Contains($"\"{name}\"", StringComparison.Ordinal))
            .Should().BeEmpty($"{site} must not register a client framework integration");
    }

    [Theory]
    [MemberData(nameof(AstroSites))]
    public void DocumentLayouts_ShouldEmitTheAstroGeneratorMarker(string site)
    {
        // The generator meta tag is how the build-output checks prove each HTML file came from Astro.
        var documentTemplates = Directory.EnumerateFiles(GetRepositoryPath(Path.Combine(site, "src")), "*.astro", SearchOption.AllDirectories)
            .Where(path => Regex.IsMatch(File.ReadAllText(path), @"<html[\s>]"))
            .ToList();

        documentTemplates.Should().NotBeEmpty();
        foreach (var template in documentTemplates)
        {
            File.ReadAllText(template).Should().Contain("<meta name=\"generator\" content={Astro.generator} />",
                $"{Path.GetRelativePath(GetRepositoryPath(site), template)} renders a full HTML document");
        }
    }

    [Fact]
    public void AstroGuarantee_ShouldBeEnforcedOnBuiltOutputs()
    {
        var vitestGuard = File.ReadAllText(GetRepositoryPath("src/WebClient/src/guarantees/astro-pages.test.ts"));
        var driftCheck = File.ReadAllText(GetRepositoryPath("scripts/check-docs-drift.py"));

        vitestGuard.Should().Contain("WebClient build output");
        vitestGuard.Should().Contain("content=\"Astro v");
        driftCheck.Should().Contain("check_astro_output(output, 'docs')");
        driftCheck.Should().Contain("check_astro_site(ROOT / path, label)");
    }

    private static string GetRepositoryPath(string relativePath)
    {
        var currentDirectory = new DirectoryInfo(AppContext.BaseDirectory);
        while (currentDirectory is not null && !File.Exists(Path.Combine(currentDirectory.FullName, "cpnucleo.slnx")))
        {
            currentDirectory = currentDirectory.Parent;
        }

        currentDirectory.Should().NotBeNull("tests should run inside the repository checkout");
        return Path.Combine(currentDirectory!.FullName, relativePath);
    }
}
