// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Cpnucleo.WebApi.Client.Models
{
    /// <summary>
    /// Request model for creating a new appointment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebApiEndpointsAppointmentCreateAppointmentRequest : IParsable
    {
        /// <summary>Gets or sets the amount of hours for the appointment.</summary>
        public int? AmountHours { get; set; }
        /// <summary>Gets or sets the unique identifier for the assignment associated with the appointment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignmentId { get; set; }
#nullable restore
#else
        public string AssignmentId { get; set; }
#endif
        /// <summary>Gets or sets the description of the appointment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Gets or sets the unique identifier for the appointment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Gets or sets the date and time when the appointment should be kept.</summary>
        public DateTimeOffset? KeepDate { get; set; }
        /// <summary>Gets or sets the name of the appointment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the unique identifier for the user associated with the appointment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsAppointmentCreateAppointmentRequest"/> and sets the default values.
        /// </summary>
        public WebApiEndpointsAppointmentCreateAppointmentRequest()
        {
            AssignmentId = "35f1a233-e070-4205-909d-0eaabf89aec4";
            Description = "Appointment description goes here";
            Id = "80aee820-ce09-4023-b62c-3a42ff4535b0";
            KeepDate = DateTimeOffset.Parse("2064-06-09");
            Name = "New Appointment";
            UserId = "35b9c5c1-6abf-4d50-aee8-00abe2f09560";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsAppointmentCreateAppointmentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsAppointmentCreateAppointmentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsAppointmentCreateAppointmentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amountHours", n => { AmountHours = n.GetIntValue(); } },
                { "assignmentId", n => { AssignmentId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "keepDate", n => { KeepDate = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("amountHours", AmountHours);
            writer.WriteStringValue("assignmentId", AssignmentId);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("keepDate", KeepDate);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("userId", UserId);
        }
    }
}
#pragma warning restore CS0618
