// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Cpnucleo.WebApi.Client.Models
{
    /// <summary>
    /// Request model for updating an assignment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebApiEndpointsAssignmentUpdateAssignmentRequest : IParsable
    {
        /// <summary>Gets or sets the amount of hours for the assignment.</summary>
        public int? AmountHours { get; set; }
        /// <summary>Gets or sets the assignment type identifier for the assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignmentTypeId { get; set; }
#nullable restore
#else
        public string AssignmentTypeId { get; set; }
#endif
        /// <summary>Gets or sets the description of the assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Gets or sets the end date of the assignment.</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>Gets or sets the unique identifier for the assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Gets or sets the name of the assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the project identifier for the assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>Gets or sets the start date of the assignment.</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>Gets or sets the user identifier for the assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>Gets or sets the workflow identifier for the assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsAssignmentUpdateAssignmentRequest"/> and sets the default values.
        /// </summary>
        public WebApiEndpointsAssignmentUpdateAssignmentRequest()
        {
            AssignmentTypeId = "6364cf0d-e617-494b-b489-36487a8427f2";
            Description = "Updated Assignment Description goes here";
            EndDate = DateTimeOffset.Parse("2069-04-20");
            Id = "35f1a233-e070-4205-909d-0eaabf89aec4";
            Name = "Updated Assignment";
            ProjectId = "8de21ef6-19a3-41ee-b4cd-ea3fae2e91c9";
            StartDate = DateTimeOffset.Parse("2069-04-20");
            UserId = "35b9c5c1-6abf-4d50-aee8-00abe2f09560";
            WorkflowId = "873eea4b-55c9-46a6-9512-4d59a77ad28b";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsAssignmentUpdateAssignmentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsAssignmentUpdateAssignmentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsAssignmentUpdateAssignmentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amountHours", n => { AmountHours = n.GetIntValue(); } },
                { "assignmentTypeId", n => { AssignmentTypeId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "projectId", n => { ProjectId = n.GetStringValue(); } },
                { "startDate", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
                { "workflowId", n => { WorkflowId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("amountHours", AmountHours);
            writer.WriteStringValue("assignmentTypeId", AssignmentTypeId);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("endDate", EndDate);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("projectId", ProjectId);
            writer.WriteDateTimeOffsetValue("startDate", StartDate);
            writer.WriteStringValue("userId", UserId);
            writer.WriteStringValue("workflowId", WorkflowId);
        }
    }
}
#pragma warning restore CS0618
