// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Cpnucleo.WebApi.Client.Models
{
    /// <summary>
    /// Response model for the list of impediments.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebApiEndpointsImpedimentListImpedimentsResponse : IParsable
    {
        /// <summary>Gets or sets the paginated result of impediments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Cpnucleo.WebApi.Client.Models.DomainModelsPaginatedResultOfImpedimentDto? Result { get; set; }
#nullable restore
#else
        public global::Cpnucleo.WebApi.Client.Models.DomainModelsPaginatedResultOfImpedimentDto Result { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentListImpedimentsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentListImpedimentsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsImpedimentListImpedimentsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "result", n => { Result = n.GetObjectValue<global::Cpnucleo.WebApi.Client.Models.DomainModelsPaginatedResultOfImpedimentDto>(global::Cpnucleo.WebApi.Client.Models.DomainModelsPaginatedResultOfImpedimentDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Cpnucleo.WebApi.Client.Models.DomainModelsPaginatedResultOfImpedimentDto>("result", Result);
        }
    }
}
#pragma warning restore CS0618
