namespace Application.UseCases.AssignmentImpediment.ListAssignmentImpediment;

public sealed record ListAssignmentImpedimentQueryViewModel(OperationResult OperationResult, PaginatedResult<AssignmentImpedimentDto?> Result);
