trigger:
- master
pr:
- master

variables:
  solution: '**/*.sln'
  project: '**/Cpnucleo.API/*.csproj'
  buildConfiguration: 'Release'  

pool:
  vmImage: 'ubuntu-20.04'

name: $(date:yyyyMMdd)$(rev:.r)

steps:

- task: UseDotNet@2
  displayName: Install .NET SDK
  inputs:
    useGlobalJson: true
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'

- powershell: |
   dotnet tool install --global dotnet-ef --ignore-failed-sources
   dotnet-ef database update --connection "Data Source=Cpnucleo.db"
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/Cpnucleo.Infra.Data/'
  displayName: 'Generate Database Migrations'

- powershell: |
   dir
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/Cpnucleo.Infra.Data/'
  displayName: 'Generate Database Migrations 2'

- powershell: |
   dir
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/Cpnucleo.API/'
  displayName: 'Generate Database Migrations 3'

- powershell: |
   ls
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/Cpnucleo.Infra.Data/'
  displayName: 'Generate Database Migrations 2'

- powershell: |
   ls
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/Cpnucleo.API/'
  displayName: 'Generate Database Migrations 3'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*.Test/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(project)'
    arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'