// <auto-generated/>
#pragma warning disable CS0618
using Cpnucleo.WebApi.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Cpnucleo.WebApi.Client.Api.Organization
{
    /// <summary>
    /// Builds and executes requests for operations under \api\organization
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrganizationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/organization?id={id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/organization?id={id}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes the organizations specified by the provided Ids. Validates existence of each, removes them, updates the repository, and commits the transaction.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationRemoveOrganizationResponse"/></returns>
        /// <param name="body">Request model for removing an organization.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationRemoveOrganizationResponse?> DeleteAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationRemoveOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationRemoveOrganizationResponse> DeleteAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationRemoveOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationRemoveOrganizationResponse>(requestInfo, global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationRemoveOrganizationResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetches the organization matching the provided Id. Returns 404 if not found, otherwise returns the organization data mapped to a DTO.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationGetOrganizationByIdResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationGetOrganizationByIdResponse?> GetAsync(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder.OrganizationRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationGetOrganizationByIdResponse> GetAsync(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder.OrganizationRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationGetOrganizationByIdResponse>(requestInfo, global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationGetOrganizationByIdResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the organization identified by the provided Id with given data. Validates existence and returns whether the update was successful.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationUpdateOrganizationResponse"/></returns>
        /// <param name="body">Request model for updating an organization.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationUpdateOrganizationResponse?> PatchAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationUpdateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationUpdateOrganizationResponse> PatchAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationUpdateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationUpdateOrganizationResponse>(requestInfo, global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationUpdateOrganizationResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new organization record with the given data and custom Id. Validates uniqueness and returns the created organization&apos;s data.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationCreateOrganizationResponse"/></returns>
        /// <param name="body">Request model for creating a new organization.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationCreateOrganizationResponse?> PostAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationCreateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationCreateOrganizationResponse> PostAsync(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationCreateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationCreateOrganizationResponse>(requestInfo, global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationCreateOrganizationResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes the organizations specified by the provided Ids. Validates existence of each, removes them, updates the repository, and commits the transaction.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request model for removing an organization.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationRemoveOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationRemoveOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, "{+baseurl}/api/organization", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Fetches the organization matching the provided Id. Returns 404 if not found, otherwise returns the organization data mapped to a DTO.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder.OrganizationRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder.OrganizationRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates the organization identified by the provided Id with given data. Validates existence and returns whether the update was successful.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request model for updating an organization.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationUpdateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationUpdateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, "{+baseurl}/api/organization", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Creates a new organization record with the given data and custom Id. Validates uniqueness and returns the created organization&apos;s data.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request model for creating a new organization.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationCreateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationCreateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/api/organization", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Fetches the organization matching the provided Id. Returns 404 if not found, otherwise returns the organization data mapped to a DTO.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationRequestBuilderGetQueryParameters 
        {
            /// <summary>Gets or sets the unique identifier for the organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id")]
            public string? Id { get; set; }
#nullable restore
#else
            [QueryParameter("id")]
            public string Id { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organization.OrganizationRequestBuilder.OrganizationRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
