namespace Application.UseCases.AssignmentImpediment.GetAssignmentImpedimentById;

public sealed record GetAssignmentImpedimentByIdQuery(Ulid Id) : IRequest<GetAssignmentImpedimentByIdQueryViewModel>;
