"""Regression proof for the Pages-base and generated-link audit; no browser required."""
import json
from runpy import run_path
import tempfile
import unittest
from pathlib import Path

checker = run_path(str(Path(__file__).with_name("check-docs-drift.py")))
check_built_site = checker["check_built_site"]
check_astro_site = checker["check_astro_site"]
check_astro_output = checker["check_astro_output"]


class GeneratedLinksTests(unittest.TestCase):
    def test_pages_base_relative_links_assets_and_fragments(self):
        # Fixtures are task-owned and stay inside the repository workspace.
        with tempfile.TemporaryDirectory(dir=Path(__file__).parent) as directory:
            root = Path(directory)
            article = root / "docs" / "article"
            article.mkdir(parents=True)
            (root / "asset.css").write_text("body {}")
            (root / "index.html").write_text('<a href="/cpnucleo/docs/article/#section">Read</a>')
            article_file = article / "index.html"
            valid = '<h1 id="section">Title</h1><a href="../../">Home</a><a href="/cpnucleo">Base</a><link href="../../asset.css"><a href="https://example.org/">External</a>'
            article_file.write_text(valid)
            check_built_site(root)
            for link, message in [
                ("../missing/", "missing local target"),
                ("#absent", "missing fragment"),
                ("/docs/article/", "escapes the Pages base"),
                ("../../../missing/", "escapes the Pages base"),
                ("../../missing.png", "missing local target"),
            ]:
                with self.subTest(link=link):
                    article_file.write_text(valid + f'<a href="{link}">Broken</a>')
                    with self.assertRaisesRegex(SystemExit, message):
                        check_built_site(root)


def make_astro_site(root):
    (root / "src" / "pages" / "docs").mkdir(parents=True)
    (root / "public").mkdir()
    (root / "src" / "pages" / "index.astro").write_text("---\n---\n<html></html>")
    (root / "src" / "pages" / "docs" / "[...slug].astro").write_text("---\n---\n<html></html>")
    (root / "public" / "robots.txt").write_text("User-agent: *")
    (root / "package.json").write_text(json.dumps({"dependencies": {"astro": "^7"}}))
    (root / "astro.config.mjs").write_text("import sitemap from '@astrojs/sitemap';")


class AstroOnlyPagesTests(unittest.TestCase):
    def test_accepts_astro_pages_and_static_assets(self):
        with tempfile.TemporaryDirectory(dir=Path(__file__).parent) as directory:
            root = Path(directory)
            make_astro_site(root)
            self.assertEqual(check_astro_site(root, "fixture"), 2)

    def test_rejects_non_astro_pages_framework_dependencies_and_public_html(self):
        cases = [
            (lambda root: (root / "src" / "pages" / "about.md").write_text("# About"), "non-Astro page src/pages/about.md"),
            (lambda root: (root / "src" / "pages" / "feed.ts").write_text("export const GET = () => {}"), "non-Astro page src/pages/feed.ts"),
            (lambda root: (root / "src" / "pages" / "old.html").write_text("<html></html>"), "non-Astro page src/pages/old.html"),
            (lambda root: (root / "public" / "legacy.html").write_text("<html></html>"), "hand-written HTML page"),
            (lambda root: (root / "package.json").write_text(json.dumps({"devDependencies": {"react": "^19"}})), "client UI framework dependency"),
            (lambda root: (root / "astro.config.mjs").write_text("import vue from '@astrojs/vue';"), "client UI framework integration"),
        ]
        for mutate, message in cases:
            with self.subTest(message=message), tempfile.TemporaryDirectory(dir=Path(__file__).parent) as directory:
                root = Path(directory)
                make_astro_site(root)
                mutate(root)
                with self.assertRaisesRegex(SystemExit, message):
                    check_astro_site(root, "fixture")

    def test_requires_astro_generated_build_output(self):
        with tempfile.TemporaryDirectory(dir=Path(__file__).parent) as directory:
            output = Path(directory)
            (output / "docs").mkdir()
            astro = '<html><head><meta name="generator" content="Astro v7.3.6"></head></html>'
            (output / "index.html").write_text(astro)
            (output / "docs" / "index.html").write_text(astro)
            self.assertEqual(check_astro_output(output, "fixture"), 2)
            (output / "docs" / "index.html").write_text("<html><head><title>Hand-written</title></head></html>")
            with self.assertRaisesRegex(SystemExit, "docs/index.html was not generated by an Astro page"):
                check_astro_output(output, "fixture")
            with self.assertRaisesRegex(SystemExit, "has no HTML pages"):
                check_astro_output(output / "missing", "fixture")


if __name__ == "__main__":
    unittest.main()
