// <auto-generated/>
#pragma warning disable CS0618
using Cpnucleo.WebApi.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Cpnucleo.WebApi.Client.Api.Organizations
{
    /// <summary>
    /// Builds and executes requests for operations under \api\organizations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrganizationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/organizations?pagination={pagination}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/organizations?pagination={pagination}", rawUrl)
        {
        }
        /// <summary>
        /// Fetches organizations based on pagination parameters, maps entities to DTOs, and returns paginated results with metadata (total count, page number, and page size).
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationListOrganizationsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationListOrganizationsResponse?> GetAsync(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder.OrganizationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationListOrganizationsResponse> GetAsync(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder.OrganizationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Cpnucleo.WebApi.Client.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationListOrganizationsResponse>(requestInfo, global::Cpnucleo.WebApi.Client.Models.WebApiEndpointsOrganizationListOrganizationsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetches organizations based on pagination parameters, maps entities to DTOs, and returns paginated results with metadata (total count, page number, and page size).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder.OrganizationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder.OrganizationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Fetches organizations based on pagination parameters, maps entities to DTOs, and returns paginated results with metadata (total count, page number, and page size).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationsRequestBuilderGetQueryParameters 
        {
            /// <summary>Gets or sets the pagination parameters for the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pagination")]
            public string? Pagination { get; set; }
#nullable restore
#else
            [QueryParameter("pagination")]
            public string Pagination { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Cpnucleo.WebApi.Client.Api.Organizations.OrganizationsRequestBuilder.OrganizationsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
