global using Application.Common.Context;
global using Application.Common.Dtos;
global using Application.Common.Models;
global using Application.Common.Repositories;
global using Domain.Entities;
global using FluentValidation;
global using Mediator;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
