global using Application.Common.Behaviors;
global using Application.Common.Models;
global using Domain.Common.Dtos;
global using Domain.Common.Repositories;
global using FluentValidation;
global using FluentValidation.Results;
global using Infrastructure.Common.Context;
global using Mediator;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Reflection;
global using ValidationException = Application.Common.Exceptions.ValidationException;
