name: Build Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  AOT: false
  TRIM: false
  EXTRA_OPTIMIZE: false
  BUILD_CONFIGURATION: Debug

jobs:
  setup-build-test:
    name: Setup, Build & Test (${{ matrix.service }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - service: WebApi
          - service: GrpcServer
          - service: IdentityApi
          - service: WebClient

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
            fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore Dependencies
        working-directory: "./src/${{ matrix.service }}"
        run: dotnet restore "${{ matrix.service }}.csproj" -p:Configuration=${${{ env.BUILD_CONFIGURATION }}} -p:AOT=${${{ env.AOT }}} -p:Trim=${${{ env.TRIM }}}

      - name: Build Application
        working-directory: "./src/${{ matrix.service }}"
        run: dotnet build "${{ matrix.service }}.csproj" -c ${{ env.BUILD_CONFIGURATION }} -p:AOT=${${{ env.AOT }}} -p:Trim=${${{ env.TRIM }}} -p:ExtraOptimize=${${{ env.EXTRA_OPTIMIZE }}}

      # - name: Unit Tests
      #   working-directory: "./test/Application.Tests"
      #   run: dotnet test

      - name: Architecture Tests
        working-directory: "./test/Architecture.Tests"
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ../../coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          directory: ./coverage
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Build and Run Docker Compose for Integration Tests
      #   run: |
      #     docker compose up db -d --build --force-recreate
      #     sleep 30

      # - name: Integration Tests
      #   working-directory: "./test/WebApi.Integration.Tests"
      #   run: dotnet test

  container-test:
    name: Container Healthcheck Test (${{ matrix.service }})
    needs: setup-build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - service: WebApi
            compose_service: webapi1-cpnucleo
            port: 5100
          - service: IdentityApi
            compose_service: identityapi-cpnucleo
            port: 5200
          - service: GrpcServer
            compose_service: grpcserver-cpnucleo
            port: 5301
          - service: WebClient
            compose_service: webclient-cpnucleo
            port: 5400

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
            fetch-depth: 0

      - name: Build and Run Docker Compose for Healthcheck Test
        run: |
          docker compose up ${{ matrix.compose_service }} -d --build --force-recreate --no-deps
          sleep 30

      - name: Test Healthcheck Endpoint
        run: |
          for i in {1..20}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:${{ matrix.port }}/healthz)
            echo "Attempt $i: Status $STATUS"
            if [ "$STATUS" -eq 200 ]; then
              echo "Healthcheck passed with status $STATUS"
              exit 0
            else
              echo "Healthcheck attempt $i failed with status $STATUS. Retrying in 5 seconds..."
              sleep 5
            fi
          done
          echo "Healthcheck failed after 20 attempts."
          exit 1
