name: Main Release IdentityApi Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AOT: false
  TRIM: true
  EXTRA_OPTIMIZE: true
  BUILD_CONFIGURATION: Release  
  DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}

jobs:
  setup-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore Dependencies
        working-directory: "./src/IdentityApi"
        run: dotnet restore "IdentityApi.csproj" -p:Configuration=${${{ env.BUILD_CONFIGURATION }}} -p:AOT=${${{ env.AOT }}} -p:Trim=${${{ env.TRIM }}}

      - name: Build Application
        working-directory: "./src/IdentityApi"      
        run: dotnet build "IdentityApi.csproj" -c ${{ env.BUILD_CONFIGURATION }} -p:AOT=${${{ env.AOT }}} -p:Trim=${${{ env.TRIM }}} -p:ExtraOptimize=${${{ env.EXTRA_OPTIMIZE }}}

      - name: Unit Tests
        working-directory: "./test/Application.Tests"
        run: dotnet test   
  
      - name: Architecture Tests
        working-directory: "./test/Architecture.Tests"
        run: dotnet test

      - name: Build and Run Docker Compose for Integration Tests
        run: |
          docker compose up db -d
          sleep 30        

      - name: Integration Tests
        working-directory: "./test/Integration.Tests"
        run: dotnet test

  build-push-image:
    needs: setup-build-test
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: Production    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./src/
          file: ./src/IdentityApi/Dockerfile
          push: true
          tags: jonathanperis/cpnucleo-identity-api:latest
          platforms: linux/amd64,linux/arm64/v8          
          build-args: |
            AOT=${{ env.AOT }}
            TRIM=${{ env.TRIM }}
            EXTRA_OPTIMIZE=${{ env.EXTRA_OPTIMIZE }}
            BUILD_CONFIGURATION=${{ env.BUILD_CONFIGURATION }}
            ASPNETCORE_ENVIRONMENT=${{ env.ASPNETCORE_ENVIRONMENT }}
            DB_CONNECTION_STRING=${{ env.DB_CONNECTION_STRING }}

  container-test:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Build and Run Docker Compose for Healthcheck Test
        run: |
          docker compose -f compose.prod.yaml up nginx -d
          sleep 30

      - name: Test Healthcheck Endpoint
        run: |
          for i in {1..20}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5200/healthz)
            echo "Attempt $i: Status $STATUS"
            if [ "$STATUS" -eq 200 ]; then
              echo "Healthcheck passed with status $STATUS"
              exit 0
            else
              echo "Healthcheck attempt $i failed with status $STATUS. Retrying in 5 seconds..."
              sleep 5
            fi
          done
          echo "Healthcheck failed after 20 attempts."
          exit 1

  deploy-image-azure:
    needs: container-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'cpnucleo-identity-api'
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_IDENTITYAPI }}
            images: 'index.docker.io/jonathanperis/cpnucleo-identity-api:latest'